# Site settings
title: tientm
header-img: img/home-bg.jpg
email: taminhtien1993@gmail.com
description: "Work hard to achieve success"
baseurl: ""
url: "http://taminhtien.github.io/"
twitter_username: taminhtien
github_username:  taminhtien
facebook_username:  tien.taminh93

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
gems: ["jemoji"]
